language: go
script: make test
notifications:
  hipchat:
    rooms:
      secure: oRlFaQSGPEs0Rgnvg13A3HTcKQH0byULQm6Ak6zLTPdNkkMMS7Sr1i0Gi+KuX22hQxRh76E6lDXxrc4D3RWix+RdjRrwP6s2KRJxTCHkx9tMOdrRQNJyEx8amwcn1/9PEymqPu2R1tm47/mNMz849KusTJ/AbWQxgDQfnjjwH5SoNuS0s0SfJKWEVaFMlHsM3PDZGZkQ41IgczGpTkwPgsCAFBlDEtMPsi0k0RqnSVriANgesNzW07N9tpVkwYBhLuIE3j7AZAY9fPY0XM2ZjDmfODu9S7BxMLSrG62YlaefPw2EdH6vv2j0kC5FWaVClBFv2EznNcyajwlnyBKJPUeN2iZjY5lMC1vjdtokFRvXf7IMMhk4ofLJg3uVkB3xcP7x3Tk71X2AVHEJ9I+RQrRW92tP5YPvNxvboyIvQvid8z+NjPrE/hFFLiAYUWNVQdqX9F6I0ols7tP3KWuPGz+sFFueY5M/+OXH3AbogJk9NFgsczlO0T8uU5KJR6A+80U6LrXKYG6TA8dvR7AAJGZXzas45ABHTng0Io8tIWhn5naJYSDN7EGErea3HtbmJlSPCgYOaO/U3Y9YMh5fnP/Lp7KPwAIy780rwCBnrNFTUaHLGHCe13WF5KkXy+lcdy/G1HG6/eFzgJ7lPeAtUxZAudfpW9z4cNBhAmcNu18=
